name: [PR Management] Auto Assign

on:
  workflow_call:

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: rancher/gh-issue-mgr/auto-assign-action@main
        with:
          configuration-path: .github/auto-assign-config.yaml
